# Copyright 2022 The IREE Authors
#
# Licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

name: Advance Upstream Forks

on:
  schedule:
    # Every hour
    - cron: "0 * * * *"

  workflow_dispatch:

jobs:
  advance_iree-llvm-fork:
    name: "Advance iree-llvm-fork"
    runs-on: ubuntu-20.04
    steps:
      - name: Checking out repository
        uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # v3.5.0
        with:
          token: ${{ secrets.WRITE_ACCESS_TOKEN }}
          repository: iree-org/iree-llvm-fork
          ref: main

      - name: Pull from upstream
        run: |
          git remote add upstream https://github.com/llvm/llvm-project.git
          git pull --ff-only upstream main
      - name: Pushing changes
        uses: ad-m/github-push-action@40bf560936a8022e68a3c00e7d2abefaf01305a6 # v0.6.0
        with:
          github_token: ${{ secrets.WRITE_ACCESS_TOKEN }}
          branch: main
          repository: iree-org/iree-llvm-fork

  advance_iree-mhlo-fork:
    name: "Advance iree-mhlo-fork"
    runs-on: ubuntu-20.04
    steps:
      - name: Checking out repository
        uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # v3.5.0
        with:
          token: ${{ secrets.WRITE_ACCESS_TOKEN }}
          repository: iree-org/iree-mhlo-fork
          ref: master

      - name: Pull from upstream
        run: |
          git remote add upstream https://github.com/tensorflow/mlir-hlo.git
          git pull --ff-only upstream master
      - name: Pushing changes
        uses: ad-m/github-push-action@40bf560936a8022e68a3c00e7d2abefaf01305a6 # v0.6.0
        with:
          github_token: ${{ secrets.WRITE_ACCESS_TOKEN }}
          branch: master
          repository: iree-org/iree-mhlo-fork

  advance_iree-tf-fork:
    name: "Advance iree-tf-fork"
    runs-on: ubuntu-20.04
    steps:
      - name: Checking out repository
        uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # v3.5.0
        with:
          token: ${{ secrets.WRITE_ACCESS_TOKEN }}
          repository: iree-org/iree-tf-fork
          ref: master

      - name: Pull from upstream
        run: |
          git remote add upstream https://github.com/tensorflow/tensorflow.git
          git pull --ff-only upstream master
      - name: Pushing changes
        uses: ad-m/github-push-action@40bf560936a8022e68a3c00e7d2abefaf01305a6 # v0.6.0
        with:
          github_token: ${{ secrets.WRITE_ACCESS_TOKEN }}
          branch: master
          repository: iree-org/iree-tf-fork

  # Since this is a proper fork we can just use the sync method.
  advance_stablehlo:
    name: "Advance StableHLO fork"
    runs-on: ubuntu-20.04
    steps:
      - name: Sync Fork
        env:
          # The normal GITHUB_TOKEN wouldn't have access to this other repo.
          GH_TOKEN: ${{ secrets.WRITE_ACCESS_TOKEN }}
        run: gh repo sync iree-org/stablehlo -b main
